### ISSUE TITLE
Using a mix of numeric and nominal data to train model

### ISSUE THREAD

**Issue by lukaszett** [maddin79/darch#15]
Hello,

in the documentation I was able to find examples for using datasets consisting of both nominal and numeric data to train the corpus. However I did not find any examples on how to use datasets containing both types of data at the same time. I tried to do it but it doesn't seem to work (yet). Is there a way to do it or is it theoretically possible to do it?

**Comment by saviola777** [comment]
Hello,

it should work, what exactly did you try, and how did it fail? The `dummyVars` function of caret will be applied to non-numeric data by default. But I'm sure there are scenarios which I have not yet considered so feel free to provide something like an MWE to illustrate the problem you encountered.

**Comment by lukaszett** [comment]
Hello,

let's say I have the following dataset as csv:
`string;x;y
"foo";12;20
"bar";7;8
"foobar";10;22
`
I then run this code:
`#input_data with Strings as factors
input_data <- read.csv(file.choose(),,sep = ";",header = T)
library(darch)
darch <- darch( y ~ .,input_data)
`

This gives me this error:
> Error in `colnames<-`(`*tmp*`, value = c("string", "x")) : 
> length of 'dimnames' [2] not equal to array extent

If I, however, use integers in the first column instead of strings it works just fine.

At the moments I'm still using darch 0.10 as 0.12 is only available as source files. The compliation for these seems to fail for me.

**Comment by saviola777** [comment]
I see. Yes, that is a problem present in version 0.10, I just tested it in 0.12 and there is no error.

Version 0.12 is available on CRAN as of today, the installation requires [Rtools](https://cran.r-project.org/bin/windows/Rtools/) if you are on Windows. If the compilation problem persists, post the error message(s) here or in a separate issue.

**Comment by lukaszett** [comment]
After using Rtools it works fine, thanks :+1:
