### ISSUE TITLE
CRAN release of 0.12

### ISSUE THREAD

**Issue by dashaub** [maddin79/darch#16]
Are there plans to release 0.12 on CRAN? I'm looking at integrating additional deep learning packages into caret (see here topepo/caret#47)and would like to build with "darch".

I see here that there have been major changes to darch.
rz1988/deeplearning#1
Clearly creating the caret integration with 0.10 wouldn't make sense if 0.12 with its major API changes will be released on CRAN soon.

**Comment by saviola777** [comment]
Hello,

yeah, the release is on its way, it should be on CRAN within the next 1-2 weeks hopefully. I already started working on a [caret integration](https://github.com/maddin79/darch/blob/master/R/caret.R), maybe you can re-use some of that.

**Comment by dashaub** [comment]
Awesome, thanks. Looking forward to the new release.
