### ISSUE TITLE
Problem with the predict.DArch example 

### ISSUE THREAD

**Issue by SatoshiReport** [maddin79/darch#21]
Looking at v0.12 of https://cran.r-project.org/web/packages/darch/darch.pdf I am using the example given for predict.DArch

```
library(darch)

data(iris)
model <- darch(Species ~ ., iris, retainData = T)
predict(model)
```

However, I receive an error:

```
WARN [2016-11-13 19:24:17] gputools package not available, using CPU matrix multiplication.
INFO [2016-11-13 19:24:17] Constructing a darch with 3 layers.
INFO [2016-11-13 19:24:17] Generating RBMs.
INFO [2016-11-13 19:24:17] Construct new RBM instance with 4 visible and 10 hidden units.
INFO [2016-11-13 19:24:17] Construct new RBM instance with 10 visible and 3 hidden units.
Error in getExecuteFunction(darch)(darch, dataSet@data) : 
  trying to get slot "data" from an object of a basic class ("NULL") with no slots
```

Any idea on how I can resolve this?

**Comment by saviola777** [comment]
Hello,

thanks for your feedback. Are you sure you are using version 0.12? Please type in `?darch` after loading the package and scroll to the bottom of the help page to check the version. What confuses me is the warning about gputools not being availble – in version 0.12, gputools is disabled by default, so I think you're using an older version.

**Comment by SatoshiReport** [comment]
I am running v0.10 - i will upgrade. I am pretty sure i got this version from install.packages("darch") however.  Thanks for the help.

**Comment by saviola777** [comment]
I see, strange. May be due to an outdated R version for which darch 0.12 is not available. I'll close this for now, you can re-open if there's anything else.
