### ISSUE TITLE
error * 0.37

### ISSUE THREAD

**Issue by alex7tula** [maddin79/darch#29]
Hi,

error calculated here darch.Learn.R line 382
```
        error[["raw"]] <- error[["raw"]] + out[1] * (1 - dot632Const)
        error[["class"]] <-
          (if (!is.na(out[2])) error[["class"]] + out[2] * (1 - dot632Const)
```
It is right if validData is exist.
If validData not exist - you show to user lowered error, but not real error.

**Comment by saviola777** [comment]
Yes, you are right, thanks for reporting it.

**Comment by alex7tula** [comment]
https://cran.r-project.org/web/packages/darch/index.html

Package ‘darch’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2018-01-27 as check problems were not corrected despite reminders.

**Comment by saviola777** [comment]
Yeah, i think @maddin79 missed their mails, I'll try to get a bit more work in and release a new, fixed version soon.
