### ISSUE TITLE
Autoencoder unrolling

### ISSUE THREAD

**Issue by j0ntt** [maddin79/darch#8]
Hi,

I suspect that the autoencoder is not implemented correctly. If you compare autoencoder of darch againt the original from

https://www.cs.toronto.edu/~hinton/science.pdf

the unrolling part is skipped in darch. In other words, darch pre-trains the whole autoencoder network from input to output and then fine-tunes it. I haven't been able to get good results with the autoencoders, although they should be superior to PCA according to the source.

**Comment by saviola777** [comment]
Hello,

thanks for your feedback. Yes, you are correct, pre-training for auto-encoders is not supported at the moment.

I guess I will add a parameter ```rbm.autoencoder``` or similar, which would then only train (given a valid network structure) up until the code layer, and copy the weights over to the decoder before fine-tuning (if I understand it correctly).

**Comment by j0ntt** [comment]
Ok. How about the biases? Looks like the weight matrices are transposed. In practice the weight of the bias term is always 1 and it is included in the matrix?

**Comment by saviola777** [comment]
During pre-training, there are biases for both layers of each RBM. Currently, the biases pointing towards the visible layer (i.e., towards the input layer of the network) are dropped when creating the layer weights for fine-tuning. I guess these could be used for the decoder?

**Comment by j0ntt** [comment]
The paper says only: 

_'After pretraining multiple layers of feature
detectors, the model is "unfolded" [ (Fig. 1) to
produce encoder and decoder networks that
initially use the same weights. The global fine-
tuning stage then replaces stochastic activities
by deterministic, real-valued probabilities and
uses backpropagation through the whole auto-
encoder to fine-tune the weights for optimal
reconstruction.'_

I think that the supporting material could confirm it: http://science.sciencemag.org/content/suppl/2006/08/04/313.5786.504.DC1

The original Matlab codes are there.

**Comment by j0ntt** [comment]
Actually, they don't even mention the biases. Perhaps what you said is correct.

**Comment by saviola777** [comment]
A quick look at the matlab code seems to confirm it as well:

```matlab
fprintf(1,'Pretraining Layer 1 with RBM: %d-%d \n',numdims,numhid);
[…]
hidrecbiases=hidbiases;
save mnistvh vishid hidrecbiases visbiases;

fprintf(1,'\nPretraining Layer 2 with RBM: %d-%d \n',numhid,numpen);
[…]
hidpen=vishid; penrecbiases=hidbiases; hidgenbiases=visbiases;
save mnisthp hidpen penrecbiases hidgenbiases;

fprintf(1,'\nPretraining Layer 3 with RBM: %d-%d \n',numpen,numpen2);
[…]
hidpen2=vishid; penrecbiases2=hidbiases; hidgenbiases2=visbiases;
save mnisthp2 hidpen2 penrecbiases2 hidgenbiases2;

fprintf(1,'\nPretraining Layer 4 with RBM: %d-%d \n',numpen2,numopen);
[…]
hidtop=vishid; toprecbiases=hidbiases; topgenbiases=visbiases;
save mnistpo hidtop toprecbiases topgenbiases;

backprop;
```

And then in backprop.m:

```matlab
%%%% PREINITIALIZE WEIGHTS OF THE AUTOENCODER %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
w1=[vishid; hidrecbiases];
w2=[hidpen; penrecbiases];
w3=[hidpen2; penrecbiases2];
w4=[hidtop; toprecbiases];
w5=[hidtop'; topgenbiases];
w6=[hidpen2'; hidgenbiases2];
w7=[hidpen'; hidgenbiases];
w8=[vishid'; visbiases];
```
